spring:
  #  data:
  #    web:
  #      pageable:
  #        one-indexed-parameters: true

  datasource:
    url: jdbc:mysql://localhost:3306/studyshop?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    database: mysql
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always